# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: JAICF documentation
tagline: Develop conversational chatbots with JAICF from Just AI
description: Develop conversational chatbots with JAICF from Just AI
baseurl: ""
url: "https://help.jaicf.com"
image: "https://help.jaicf.com/assets/images/jaicf-banner.png"
twitter_username: JustAIglobal
github_username:  just-ai
author: Just AI

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

aux_links:
  "Get JAICF on GitHub":
    - "//github.com/just-ai/jaicf-kotlin"

aux_links_new_tab: true
